# Generated by Django 6.0.3 on 2026-03-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
