# Generated by Django 6.0.3 on 2026-03-24 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_empleado_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_am', models.CharField(max_length=100)),
                ('descripcion_am', models.TextField(blank=True, null=True)),
                ('direccion_am', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Almacenes',
                'ordering': ['nombre_am'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ct', models.CharField(max_length=100)),
                ('descripcion_ct', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre_ct'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pr', models.CharField(max_length=100)),
                ('nombre_tc', models.CharField(max_length=100)),
                ('fecha_fab', models.DateField()),
                ('fecha_venc', models.DateField()),
                ('descripcion_pr', models.TextField(blank=True, null=True)),
                ('concentracion_qm', models.CharField(blank=True, max_length=100, null=True)),
                ('composicion_qm', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='personas.categoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre_pr'],
            },
        ),
    ]
