# Generated by Django 6.0.3 on 2026-03-24 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_almacen_categoria_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='personas.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenes', to='personas.producto')),
            ],
            options={
                'verbose_name_plural': 'Producto Almacen',
                'ordering': ['producto', 'almacen'],
                'unique_together': {('producto', 'almacen')},
            },
        ),
    ]
