# Generated by Django 6.0.3 on 2026-03-24 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_productoalmacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_dv', models.IntegerField()),
                ('precio_dv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta', to='personas.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta', to='personas.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='personas.venta')),
            ],
            options={
                'verbose_name_plural': 'Detalles Venta',
                'ordering': ['venta', 'producto'],
                'unique_together': {('venta', 'producto', 'almacen')},
            },
        ),
    ]
